server:
  port: 8086
spring:
  datasource:
    password: password
    url: jdbc:h2:file:/home/plotn/Projects/plotnCleverNest/db/clever_nest_db
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: CNEST
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        use_sql_comments: true
    show-sql: true
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: WARN
app:
  err_include_stacktrace: 1
  data:
    folder: /home/plotn/Projects/plotnCleverNest/data/
  log:
    folder: /home/plotn/Projects/plotnCleverNest/log/
openexchangerates:
  url: https://openexchangerates.org/api/latest.json
  app_id: 7a63e90cc2c14efc868ecdaa7061fed2
javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  # Data source names to exclude from monitoring (optional, comma-separated)
  #excluded-datasources: secretSource,topSecretSource
  # Enable monitoring of Spring services and controllers (optional, default: true)
  spring-monitoring-enabled: true
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests:
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to aggregate digits in http requests:
    #http-transform-pattern: \d+
    # to add basic auth:
    #authorized-users: admin:pwd
    # to change the default storage directory:
    #storage-directory: /tmp/javamelody
    # to change the default "/monitoring" path:
    #monitoring-path: /admin/performance